// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPrYyAEztTHD_eXiF2IidsMwnSJkbq3V8',
    appId: '1:969619508920:web:176bd42b7bbcce1bad6e4d',
    messagingSenderId: '969619508920',
    projectId: 'chat-app-577f8',
    authDomain: 'chat-app-577f8.firebaseapp.com',
    storageBucket: 'chat-app-577f8.appspot.com',
    measurementId: 'G-KYYJF1PVV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYMALa2posRHtYlhUDtPemifV1Kmd9t_s',
    appId: '1:969619508920:android:1d4daa9460ef94d1ad6e4d',
    messagingSenderId: '969619508920',
    projectId: 'chat-app-577f8',
    storageBucket: 'chat-app-577f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNWWHMmZPhwA-wVMRiq5CvzSAB_Rxebgw',
    appId: '1:969619508920:ios:0e9bced460a97f22ad6e4d',
    messagingSenderId: '969619508920',
    projectId: 'chat-app-577f8',
    storageBucket: 'chat-app-577f8.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNWWHMmZPhwA-wVMRiq5CvzSAB_Rxebgw',
    appId: '1:969619508920:ios:0e9bced460a97f22ad6e4d',
    messagingSenderId: '969619508920',
    projectId: 'chat-app-577f8',
    storageBucket: 'chat-app-577f8.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPrYyAEztTHD_eXiF2IidsMwnSJkbq3V8',
    appId: '1:969619508920:web:20145ac8c9c1a2d9ad6e4d',
    messagingSenderId: '969619508920',
    projectId: 'chat-app-577f8',
    authDomain: 'chat-app-577f8.firebaseapp.com',
    storageBucket: 'chat-app-577f8.appspot.com',
    measurementId: 'G-NZYX6J51XL',
  );
}
